'use client'
import Header from '@components/components/Header'
import './globals.css'
import { Bruno_Ace, Fira_Sans, Inter, PT_Sans } from 'next/font/google'
import Footer from '@components/components/Footer'
import { usePathname } from 'next/navigation'
import { SessionProvider, useSession } from 'next-auth/react';
import Layout from '@components/components/Layout'

const inter = Fira_Sans({ 
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-inter'
})
 
 

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children, session }) { 

  return (
    <SessionProvider session={session}> 
      <html lang="en" className={`${inter.className}`}>
        <body>
          <Layout> 
            {children} 
          </Layout> 
        </body>
      </html>
    </SessionProvider>
  )
}
