'use client'
import Header from '@components/components/Header'
import './globals.css'
import { Bruno_Ace, Fira_Sans, Inter, PT_Sans } from 'next/font/google'
import Footer from '@components/components/Footer'
import { usePathname } from 'next/navigation'
import { SessionProvider, useSession } from 'next-auth/react';

const inter = Inter({ 
  subsets: ['latin'],
  variable: '--font-inter'
})
const pt_sans = Fira_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-pt'
})
const bruno = Bruno_Ace({
  subsets: ['latin'],
  weight: ['400'],
  display: 'swap',
  variable: '--font-bruno'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, session }) {
 
  console.log(session);
  const routerpath = usePathname();
  // console.log(routerpath);

  if(routerpath === '/login' || routerpath === '/signup') {
    return (
      <html lang="en">
        <body className={`${inter.className} ${bruno.className}`}>
       
          {children}
       
        </body>
      </html>
    )
  }

  return (
    <SessionProvider session={session}> 
      <html lang="en" className={`${inter.className} ${bruno.className}`}>
        <body>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </SessionProvider>
  )
}
